(function () {
  'use strict';
  var KEY = 'est60_app_profile_v1';
  var TASKS_KEY = 'est60_app_tasks_v1';
  var DONE_KEY = 'est60_app_done_public_v1';
  var ALERTS_KEY = 'est60_app_alerts_seen_v1';
  var defaults = { name: '', theme: 'dark', favorites: ['Inglés', 'Tecnología'] };
  function read(key, fallback) { try { var v = localStorage.getItem(key); return v ? JSON.parse(v) : fallback; } catch (_) { return fallback; } }
  function write(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch (_) { return false; } }
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (ch) { if (ch === '&') return '&amp;'; if (ch === '<') return '&lt;'; if (ch === '>') return '&gt;'; if (ch === '"') return '&quot;'; return '&#39;'; }); }
  function todayKey() { var d = new Date(); return d.getFullYear() + '-' + String(d.getMonth()+1).padStart(2,'0') + '-' + String(d.getDate()).padStart(2,'0'); }
  function dateLabel(value) { if (!value) return 'Sin fecha'; var d = new Date(value + (String(value).length === 10 ? 'T12:00:00' : '')); return isNaN(d.getTime()) ? value : d.toLocaleDateString('es-MX',{day:'numeric',month:'short'}); }
  var profile = Object.assign({}, defaults, read(KEY, {}));
  var personalTasks = read(TASKS_KEY, []);
  var completedPublic = read(DONE_KEY, []);
  var seenAlerts = read(ALERTS_KEY, []);
  var root;
  function createPanel() {
    if (document.getElementById('est60AppSpace')) return;
    /* Los estilos exclusivos se cargan desde app-extras.css. */
    root = document.createElement('section'); root.id = 'est60AppSpace'; root.className = 'est60-app-space';
    root.innerHTML = '<div class="ea-top"><div><span class="ea-kicker">EXCLUSIVO DE LA APP</span><h2>Mi espacio <span>1°D</span></h2><p id="eaGreeting">Tu centro personal para la escuela.</p></div><button type="button" id="eaSettingsOpen" class="ea-icon-btn" aria-label="Personalizar">⚙</button></div>' +
      '<div class="ea-profile"><div class="ea-avatar" id="eaAvatar">1D</div><div class="ea-profile-text"><strong id="eaProfileName">Alumno de 1°D</strong><span>Tu panel personal · se guarda en este celular</span></div><button type="button" id="eaEditProfile" class="ea-quiet-btn">Editar</button></div>' +
      '<div class="ea-stats"><div><span>Tareas personales</span><strong id="eaTaskCount">0</strong></div><div><span>Por completar</span><strong id="eaPendingCount">0</strong></div><div><span>Avisos nuevos</span><strong id="eaAlertCount">0</strong></div></div>' +
      '<div class="ea-card ea-now"><div class="ea-card-heading"><span class="ea-kicker">HORARIO INTELIGENTE</span><span class="ea-live-dot"></span></div><strong id="eaCurrentClass">Consultando horario…</strong><p id="eaCurrentMessage">Se actualizará al leer el horario del grupo.</p><div class="ea-next"><span>PRÓXIMA CLASE</span><strong id="eaNextClass">Calculando…</strong><small id="eaNextTime">Consulta el horario completo abajo.</small></div><button type="button" class="ea-link-btn" data-target="horario">Abrir horario completo →</button></div>' +
      '<div class="ea-section-title"><div><span class="ea-kicker">ORGANÍZATE</span><h3>Mis tareas</h3></div><button type="button" id="eaAddTaskOpen" class="ea-primary-btn">+ Añadir</button></div>' +
      '<form id="eaTaskForm" class="ea-task-form" hidden><label>¿Qué tienes que hacer?<input id="eaTaskTitle" maxlength="120" required placeholder="Ej. Terminar actividad de Geografía"></label><div class="ea-form-row"><label>Materia<input id="eaTaskSubject" maxlength="50" placeholder="Geografía"></label><label>Entrega<input id="eaTaskDate" type="date"></label></div><div class="ea-form-actions"><button type="button" id="eaCancelTask" class="ea-quiet-btn">Cancelar</button><button class="ea-primary-btn" type="submit">Guardar tarea</button></div></form>' +
      '<div id="eaTaskList" class="ea-task-list"></div><div class="ea-empty" id="eaTaskEmpty">Todavía no agregas tareas personales. Puedes guardar trabajos aquí y marcarlos cuando termines.</div>' +
      '<div class="ea-section-title ea-notice-title"><div><span class="ea-kicker">CENTRO DE AVISOS</span><h3>Novedades del grupo</h3></div><button type="button" id="eaRefresh" class="ea-quiet-btn">Actualizar</button></div><div id="eaNoticeList" class="ea-notice-list"></div>' +
      '<div class="ea-section-title"><div><span class="ea-kicker">A TU MANERA</span><h3>Personalización</h3></div></div><div class="ea-settings"><label>Cómo quieres que te llamemos<input id="eaNameInput" maxlength="32" placeholder="Tu apodo"></label><label>Tema de la app<select id="eaThemeSelect"><option value="dark">Azul oscuro</option><option value="light">Claro</option></select></label><div class="ea-fav-wrap"><span>Materias favoritas</span><div id="eaFavorites" class="ea-favorites"></div></div><button type="button" id="eaSaveSettings" class="ea-primary-btn">Guardar preferencias</button><p id="eaSaveMessage" role="status"></p></div>' +
      '<div class="ea-offline-note"><span>✓</span><p><strong>Tus datos personales se quedan en este dispositivo.</strong><br>Las tareas, el apodo, el tema y las materias favoritas se conservan sin conexión. Los avisos del grupo se actualizan cuando hay internet y pueden mostrarse desde la última copia guardada.</p></div>' +
      '<div class="ea-bottom-links"><button type="button" data-target="avisos">Avisos del grupo</button><button type="button" data-target="tareas">Tareas públicas</button><button type="button" data-target="calendario">Calendario</button></div>';
    var main = document.querySelector('main'); if (main) main.insertBefore(root, main.firstChild);
    root.querySelector('#eaSettingsOpen').addEventListener('click', function () { root.querySelector('.ea-settings').scrollIntoView({behavior:'smooth',block:'center'}); root.querySelector('#eaNameInput').focus(); });
    root.querySelector('#eaEditProfile').addEventListener('click', function () { root.querySelector('.ea-settings').scrollIntoView({behavior:'smooth',block:'center'}); root.querySelector('#eaNameInput').focus(); });
    root.querySelector('#eaAddTaskOpen').addEventListener('click', function () { var f=root.querySelector('#eaTaskForm'); f.hidden=!f.hidden; if(!f.hidden) root.querySelector('#eaTaskTitle').focus(); });
    root.querySelector('#eaCancelTask').addEventListener('click', function () { root.querySelector('#eaTaskForm').hidden=true; });
    root.querySelector('#eaTaskForm').addEventListener('submit', function (event) { event.preventDefault(); var title=root.querySelector('#eaTaskTitle').value.trim(); if(!title)return; personalTasks.unshift({id:Date.now().toString(36)+Math.random().toString(36).slice(2,7),title:title,subject:root.querySelector('#eaTaskSubject').value.trim(),date:root.querySelector('#eaTaskDate').value,done:false,created:todayKey()}); write(TASKS_KEY,personalTasks); event.target.reset(); event.target.hidden=true; renderTasks(); renderStats(); notify('Tarea guardada','Se agregó a tu lista personal.'); });
    root.querySelector('#eaTaskList').addEventListener('change', function (event) { var id=event.target.getAttribute('data-task-done'); if(!id)return; var task=personalTasks.find(function(t){return t.id===id;}); if(task){task.done=event.target.checked;write(TASKS_KEY,personalTasks);renderTasks();renderStats();} });
    root.querySelector('#eaTaskList').addEventListener('click', function (event) { var btn=event.target.closest('[data-task-delete]'); if(!btn)return; personalTasks=personalTasks.filter(function(t){return t.id!==btn.getAttribute('data-task-delete');});write(TASKS_KEY,personalTasks);renderTasks();renderStats(); });
    root.querySelector('#eaSaveSettings').addEventListener('click', saveSettings);
    root.querySelector('#eaRefresh').addEventListener('click', function () { refreshNotices(); notify('Centro de avisos','Se revisaron los avisos y las tareas que están visibles en la app.'); });
    root.addEventListener('click', function(event){var btn=event.target.closest('[data-target]');if(!btn)return;var target=document.getElementById(btn.getAttribute('data-target'));if(target)target.scrollIntoView({behavior:'smooth',block:'start'});});
    root.querySelector('#eaNameInput').value=profile.name||''; root.querySelector('#eaThemeSelect').value=profile.theme||'dark';
    var subjects=['Español','Matemáticas','Inglés','Geografía','Ciencias','Tecnología','Historia','Artes','Educación Física','Tutoría','Formación Cívica y Ética'];
    root.querySelector('#eaFavorites').innerHTML=subjects.map(function(s){return '<label class="ea-fav"><input type="checkbox" value="'+esc(s)+'" '+(profile.favorites.indexOf(s)>=0?'checked':'')+'><span>'+esc(s)+'</span></label>';}).join('');
    renderProfile(); applyTheme(); renderTasks(); renderStats(); updateSchedule(); refreshNotices();
    var schedule=document.getElementById('smartSchedule'); if(schedule && window.MutationObserver){new MutationObserver(updateSchedule).observe(schedule,{childList:true,subtree:true,characterData:true,attributes:true});}
    var publicTasks=document.getElementById('tareasPublicas'); if(publicTasks && window.MutationObserver){new MutationObserver(function(){renderPublicTasks();renderStats();refreshNotices();}).observe(publicTasks,{childList:true,subtree:true,characterData:true});}
    var publicNotices=document.getElementById('avisosPublicos'); if(publicNotices && window.MutationObserver){new MutationObserver(function(){refreshNotices();renderStats();}).observe(publicNotices,{childList:true,subtree:true,characterData:true});}
    window.addEventListener('online', function(){root.classList.remove('ea-offline');}); window.addEventListener('offline', function(){root.classList.add('ea-offline');});
    if(!navigator.onLine)root.classList.add('ea-offline');
    setInterval(function(){updateSchedule();refreshNotices();},60000);
  }
  function renderProfile(){var name=profile.name.trim()||'Alumno de 1°D';root.querySelector('#eaProfileName').textContent=name;root.querySelector('#eaAvatar').textContent=profile.name.trim()?profile.name.trim().slice(0,2).toUpperCase():'1D';root.querySelector('#eaGreeting').textContent=profile.name.trim()?'Qué tal, '+profile.name.trim()+'. Aquí tienes tu día escolar.':'Tu centro personal para organizar el día escolar.';}
  function applyTheme(){if(!root)return;root.classList.toggle('ea-light',profile.theme==='light');}
  function saveSettings(){profile.name=root.querySelector('#eaNameInput').value.trim();profile.theme=root.querySelector('#eaThemeSelect').value;profile.favorites=Array.from(root.querySelectorAll('#eaFavorites input:checked')).map(function(i){return i.value;});write(KEY,profile);renderProfile();applyTheme();root.querySelector('#eaSaveMessage').textContent='Preferencias guardadas en este dispositivo.';notify('Preferencias guardadas','Tu apodo, tema y materias favoritas se guardaron en este celular.');}
  function notify(title,message){if(!root)return;var box=root.querySelector('#eaSaveMessage');if(box){box.textContent=title+': '+message;box.classList.add('ea-message-show');setTimeout(function(){box.classList.remove('ea-message-show');},4500);}}
  function renderTasks(){if(!root)return;var list=root.querySelector('#eaTaskList');var empty=root.querySelector('#eaTaskEmpty');empty.hidden=personalTasks.length>0;list.innerHTML=personalTasks.map(function(t){var late=t.date&&!t.done&&t.date<todayKey();var soon=t.date&&!t.done&&t.date>=todayKey()&&t.date<=new Date(Date.now()+86400000).toISOString().slice(0,10);return '<article class="ea-task '+(t.done?'is-done':'')+'"><label class="ea-task-check"><input type="checkbox" data-task-done="'+esc(t.id)+'" '+(t.done?'checked':'')+'><span class="ea-checkmark"></span></label><div class="ea-task-main"><strong>'+esc(t.title)+'</strong><div class="ea-task-meta">'+(t.subject?'<span>'+esc(t.subject)+'</span>':'<span>Personal</span>')+(t.date?'<span class="'+(late?'ea-late':soon?'ea-soon':'')+'">Entrega: '+esc(dateLabel(t.date))+(late?' · vencida':soon?' · próxima':'')+'</span>':'')+'</div></div><button type="button" data-task-delete="'+esc(t.id)+'" class="ea-delete" aria-label="Eliminar tarea">×</button></article>';}).join('');}
  function renderStats(){if(!root)return;var pending=personalTasks.filter(function(t){return !t.done;}).length;var count=root.querySelector('#eaTaskCount');var pend=root.querySelector('#eaPendingCount');if(count)count.textContent=personalTasks.length;if(pend)pend.textContent=pending;var alertCount=root.querySelector('#eaAlertCount');if(alertCount)alertCount.textContent=getAlerts().filter(function(a){return seenAlerts.indexOf(a.id)<0;}).length;}
  function updateSchedule(){if(!root)return;var cur=document.getElementById('smartCurrentSubject');var msg=document.getElementById('smartCurrentMessage');var next=document.getElementById('smartNextSubject');var nextTime=document.getElementById('smartNextTime');root.querySelector('#eaCurrentClass').textContent=cur?cur.textContent.trim():'Abre el horario para consultar';root.querySelector('#eaCurrentMessage').textContent=msg?msg.textContent.trim():'El horario inteligente está disponible más abajo.';root.querySelector('#eaNextClass').textContent=next?next.textContent.trim():'Consulta el horario completo';root.querySelector('#eaNextTime').textContent=nextTime?nextTime.textContent.trim():'Horario de 1°D';}
  function publicTaskItems(){var c=document.getElementById('tareasPublicas');if(!c)return [];return Array.from(c.querySelectorAll('.task-card')).map(function(el,i){return {id:'public-'+i,title:(el.querySelector('h3')||{}).textContent||'Tarea del grupo',detail:el.innerText||'',done:completedPublic.indexOf('public-'+i)>=0};}).filter(function(t){return t.title.indexOf('Cargando')<0&&t.title.indexOf('No se pudieron')<0&&t.title.indexOf('No hay tareas')<0;});}
  function renderPublicTasks(){if(!root)return;var existing=root.querySelector('#eaPublicTaskBlock');if(existing)existing.remove();var items=publicTaskItems();if(!items.length)return;var block=document.createElement('div');block.id='eaPublicTaskBlock';block.className='ea-public-tasks';block.innerHTML='<div class="ea-public-head"><strong>Tareas publicadas para el grupo</strong><span>Marca las que ya terminaste</span></div>'+items.map(function(t){return '<label class="ea-public-task"><input type="checkbox" data-public-done="'+esc(t.id)+'" '+(t.done?'checked':'')+'><span><strong>'+esc(t.title)+'</strong><small>'+esc(t.detail.replace(t.title,'').trim().slice(0,120))+'</small></span></label>';}).join('');root.querySelector('#eaTaskList').insertAdjacentElement('afterend',block);block.addEventListener('change',function(e){var id=e.target.getAttribute('data-public-done');if(!id)return;if(e.target.checked){if(completedPublic.indexOf(id)<0)completedPublic.push(id);}else{completedPublic=completedPublic.filter(function(x){return x!==id;});}write(DONE_KEY,completedPublic);renderPublicTasks();renderStats();});}
  function getAlerts(){var alerts=[];var n=document.getElementById('avisosPublicos');if(n){Array.from(n.querySelectorAll('.notice-card')).forEach(function(el,i){var title=(el.querySelector('h3')||{}).textContent||'';var body=(el.querySelector('p')||{}).textContent||'';if(title&&title.indexOf('Cargando')<0&&title.indexOf('No se pudieron')<0&&title.indexOf('No hay avisos')<0)alerts.push({id:'notice-'+title+'-'+body,title:title,body:body,type:'Aviso'});});}var ev=document.getElementById('eventosPublicos');if(ev){Array.from(ev.querySelectorAll('.calendar-card')).forEach(function(el){var title=(el.querySelector('strong')||{}).textContent||'';var body=(el.querySelector('p')||{}).textContent||'';if(title&&title.indexOf('Cargando')<0&&title.indexOf('Error al cargar')<0&&title.indexOf('No hay eventos')<0)alerts.push({id:'event-'+title,title:title,body:body,type:'Evento'});});}personalTasks.filter(function(t){return !t.done&&t.date;}).forEach(function(t){alerts.push({id:'task-'+t.id,title:t.title,body:'Entrega: '+dateLabel(t.date),type:t.date<todayKey()?'Tarea vencida':'Recordatorio de tarea'});});return alerts;}
  function refreshNotices(){if(!root)return;var items=getAlerts();var list=root.querySelector('#eaNoticeList');if(!items.length){list.innerHTML='<div class="ea-notice-empty">No hay avisos nuevos por mostrar. Cuando se publiquen novedades, aparecerán aquí.</div>';renderStats();return;}list.innerHTML=items.slice(0,8).map(function(a){var fresh=seenAlerts.indexOf(a.id)<0;return '<article class="ea-notice-item '+(fresh?'is-new':'')+'"><span class="ea-notice-icon">'+(a.type==='Evento'?'CAL':a.type.indexOf('Tarea')>=0?'TAR':'AVS')+'</span><div><span class="ea-notice-type">'+esc(a.type)+(fresh?' · NUEVO':'')+'</span><strong>'+esc(a.title)+'</strong><p>'+esc(a.body).slice(0,180)+'</p></div></article>';}).join('');items.forEach(function(a){if(seenAlerts.indexOf(a.id)<0)seenAlerts.push(a.id);});write(ALERTS_KEY,seenAlerts.slice(-300));renderStats();renderPublicTasks();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',createPanel);else createPanel();
})();